name: 'Setup KubeSolo'
description: 'Install and configure KubeSolo - Ultra-lightweight single-node Kubernetes for CI/CD'
author: 'fenio'

branding:
  icon: 'box'
  color: 'blue'

inputs:
  version:
    description: 'KubeSolo version to install (e.g., v0.1.7-beta, latest)'
    required: false
    default: 'latest'
  
  wait-for-ready:
    description: 'Wait for KubeSolo cluster to be ready before completing'
    required: false
    default: 'true'
  
  timeout:
    description: 'Timeout in seconds to wait for cluster readiness'
    required: false
    default: '120'
  
  dns-readiness:
    description: 'Wait for CoreDNS to be ready and verify DNS resolution works'
    required: false
    default: 'true'
  
  local-storage-shared-path:
    description: 'Path for shared local storage (enables ReadWriteMany PVCs). If set, configures local-path-provisioner with sharedFileSystemPath.'
    required: false
    default: ''

outputs:
  kubeconfig:
    description: 'Path to the kubeconfig file'
    value: ${{ steps.setup.outputs.kubeconfig }}

runs:
  using: 'composite'
  steps:
    - name: Setup KubeSolo
      id: setup
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_WAIT_FOR_READY: ${{ inputs.wait-for-ready }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_DNS_READINESS: ${{ inputs.dns-readiness }}
        INPUT_LOCAL_STORAGE_SHARED_PATH: ${{ inputs.local-storage-shared-path }}
      run: ${{ github.action_path }}/setup.sh

