name: 'Setup KubeSolo'
description: 'Install and configure KubeSolo - Ultra-lightweight single-node Kubernetes for CI/CD'
author: 'fenio'

branding:
  icon: 'box'
  color: 'blue'

inputs:
  version:
    description: 'KubeSolo version to install (e.g., v0.1.7-beta, latest)'
    required: false
    default: 'latest'
  
  wait-for-ready:
    description: 'Wait for KubeSolo cluster to be ready before completing'
    required: false
    default: 'true'
  
  timeout:
    description: 'Timeout in seconds to wait for cluster readiness'
    required: false
    default: '60'

outputs:
  kubeconfig:
    description: 'Path to the kubeconfig file'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'

